import type { Metadata } from 'next';
import './globals.css';
import { Noto_Sans, Short_Stack } from 'next/font/google';
import { Providers } from "./providers";
import { Toaster } from 'sonner';
import Navbar from './components/Navbar';
import SectionalBrandOverlay from './components/SectionalBrandOverlay';

export const runtime = "edge";

const notosans = Noto_Sans({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans',
})
const shortStack = Short_Stack({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-short-stack'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" title="ClothME">
      <body suppressHydrationWarning={true} className={`${notosans.variable} ${shortStack.variable}`}>
        {/* <header
          className="absolute inset-x-0 top-0 flex justify-between items-center max-w-7xl mx-auto py-4 px-5 h-7"
        >
          <SectionalBrandOverlay base gap="gap-4" className="flex-row-reverse" />
          <Navbar />
        </header> */}
        <Providers>
          {/* <main> */}
            {children}
          {/* </main> */}
        </Providers>
        <Toaster position="top-right" />
      </body>
    </html>
  )
}
